name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.4', head]
      fail-fast: false
    continue-on-error: ${{ matrix.ruby == 'head' }}
    env:
      BUNDLE_BUILD__TORCH___RB: "--with-torch-dir=/home/runner/libtorch"
      LIBTORCH_VERSION: 2.5.1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/libtorch
          key: libtorch-${{ env.LIBTORCH_VERSION }}
        id: cache-libtorch

      - name: Download LibTorch
        if: steps.cache-libtorch.outputs.cache-hit != 'true'
        run: |
          cd ~
          wget -q -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-$LIBTORCH_VERSION%2Bcpu.zip
          unzip -q libtorch.zip

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake
